### ISSUE TITLE
Release via npm

### ISSUE THREAD

**Issue by Dominic-Marcelino** [utomic-media/directus-extension-field-actions#1]
In order to have an easier installation we should release the extension on npm (as it's open source now)

Therefore we need to find out how we can install both extension types from one folder
https://github.com/utomic-media/directus-extension-field-actions/issues/1#issue-1348416119
https://github.com/directus/directus/discussions/15001#discussion-4293577

**Comment by SergeyRe** [comment]
i think you can publish 2 extentions separately

**Comment by Dominic-Marcelino** [comment]
> i think you can publish 2 extentions separately

This would be possible, but as they are build to work together we'd like to keep them bundled. I'll re-check the bundle options within the next weeks as I think there's some (still undocumented) new options

**Comment by SergeyRe** [comment]
i use directus on kubernetes - the way to install extension before directus starts is the most simple and clear -just one more string

**Comment by staminna** [comment]
@SergeyRe can you please elaborate or provide a link or how to achieved this? I am using Docker Container for Directus on AWS but I don't know how to mount the extensions? Thanks.

**Comment by SergeyRe** [comment]
> @SergeyRe can you please elaborate or provide a link or how to achieved this? I am using Docker Container for Directus on AWS but I don't know how to mount the extensions? Thanks.

Not sure that is optimal way of adding extensions but it works
` command: ["sh", "-c"]
          args:
            [
              "npm i directus-extension-m2m-conditions && npm i directus-extension-vgrid-interface && npx directus start",
            ]`

**Comment by SergeyRe** [comment]
> > i think you can publish 2 extentions separately
> 
> This would be possible, but as they are build to work together we'd like to keep them bundled. I'll re-check the bundle options within the next weeks as I think there's some (still undocumented) new options.
> 
> Until then you can download the two release-files from the [release page](https://github.com/utomic-media/directus-extension-field-actions/releases) and copy them into the extensions folders

check [this duscussion](https://github.com/directus/directus/discussions/8550)  and [this example](https://github.com/dimitrov-adrian/directus-extension-linkmeta). Hope it will be useful

**Comment by SergeyRe** [comment]
Sorry for pointing old approach 
The latest is use bundle type of extension
Just made first bundle of 2 interface extensions using one in  another 
[check here](https://www.npmjs.com/package/directus-extension-tri-state-options?activeTab=explore)

**Comment by Dominic-Marcelino** [comment]
We've refactored the extension into bundle containing the display + interface and released it on npm.
It can now be installed through 

```
npm i directus-extension-field-actions
```

or 

```
pnpm i directus-extension-field-actions
```
