### ISSUE TITLE
CSS around the field not showing.

### ISSUE THREAD

**Issue by staminna** [utomic-media/directus-extension-field-actions#10]
Dear utomic-media

Thank you for the extension.
The extension is enabled and I even manually added the CSS from .vue file in the project settings field, but the field is not highlighted  

```
.action-interface {
	display: flex;
	flex-direction: row;
	align-items: center;
	.v-button {
		margin-left: 1rem;
	}
}
```

Isn't it included on the index.js file? What am I missing? Others might miss it also, help is appreciated.

Thanks!

**Comment by Dominic-Marcelino** [comment]
Olá Jorge 🇵🇹
Thanks for using the extension! 
Sorry for my late reply, I somehow missed your issue.

By default the interface does not uses and custom colors as you can also see in this screenshot from the readme: 
https://github.com/utomic-media/directus-extension-field-actions/raw/main/docs/screenshots/item-copy-button.png 

The code you've mentioned is included in the build index.js file and doesn't need to be added into the directus custom-css field (and it's also not possible, as it's using SCSS which needs to be compiled).

What exactly do you want to style?

**Comment by staminna** [comment]
Olá Dominic ;)

Thanks, I think I confused the repo with another similar extension name for Directus.
It is working as expected.

Best
Jorge
