### ISSUE TITLE
Manual installation from one folder

### ISSUE THREAD

**Issue by Dominic-Marcelino** [utomic-media/directus-extension-field-actions#2]
Check if we can provide any easier manual installation method than copying both files to each of its folder (`displays/field-actions` and `interfaces/field-actions`).

A possible solution could be the `pack` extemsion type but seems that this is npm only?
https://github.com/directus/directus/discussions/15001#discussion-4293577

See also:
https://github.com/utomic-media/directus-extension-field-actions/issues/1#issue-1348416119

**Comment by Dominic-Marcelino** [comment]
Update: the extension is refactored into an extension-bundle. This allows serving both extensions at one, but only supports installations via npm right now

**Comment by anantakrishna** [comment]
> only supports installations via npm right now

Here is described a way of manual installing a bundle extension into a self-hosted Directus in Docker: https://discord.com/channels/725371605378924594/1090590039790063638

Basically, place a folder directly in the `extensions` folder:
![image](https://github.com/utomic-media/directus-extension-field-actions/assets/6065071/96620826-6624-4959-9bf4-267cf78cd3ee)

**Comment by Dominic-Marcelino** [comment]
Thanks for letting me know! Didn't knew that bundle extensions are finally supported from local extensions folder. Will update the guide and gh-release action

closed in ea15a1f35874773f8e7fceff99bf24e71fd12b9c

**Comment by anantakrishna** [comment]
> bundle extensions are finally supported from local extensions folder

I feel it is more a workaround yet. But at least feasible, I've used it.
