### ISSUE TITLE
problem in One to Many table view

### ISSUE THREAD

**Issue by hellosunghyun** [utomic-media/directus-extension-field-actions#27]
<img width="801" alt="CleanShot 2023-03-21 at 23 38 57@2x" src="https://user-images.githubusercontent.com/96941616/226640874-9f559d32-d678-47dd-9afc-162839c2ac4b.png">

When the display method is enabled in One to Many, the display is displayed only as ...

**Comment by Dominic-Marcelino** [comment]
What version are you using? This should be resolved in #23 (released in v1.4.1)
