### ISSUE TITLE
Add a way (or default behaviour) to open link in a new window

### ISSUE THREAD

**Issue by BenoitAverty** [utomic-media/directus-extension-field-actions#28]
Hello,

There is a difference in the behaviour of the "open link" button and the "open link" action when clicking the value.

The button has a target="_blank" attribute but the link on the value does not. Also, the button behaves correctly regarding the #26 issue.

I would like to have the link open in a new window. I'd be fine with an option allowing both cases.

Thanks in advance, please tell if you'd like me to open a PR.

**Comment by Dominic-Marcelino** [comment]
Thanks for reporting. Will fix this the next days!
By default we want all links to open in a new tab, but I do see the advantage to open them in the same tab (in case of internal linking). Will take a setting into consideration. 
Will be fixed together with #26

**Comment by BenoitAverty** [comment]
My use case is to open in a new window. While I see the advantage of a setting, this is not a setting I would use for now.
