### ISSUE TITLE
Replace string with a specific character to show

### ISSUE THREAD

**Issue by hellosunghyun** [utomic-media/directus-extension-field-actions#33]
This is a suggestion for a feature that would be nice to have.

How about adding a Replace String item in the Display?

I mainly use this extension for URL entries, as a button for the entered URL.
If you add the ability to show certain characters (like "Button" or "Click") instead of showing the URL, it would be possible to use the extension as a button in a table.
This would solve the problem of too long URLs being truncated.

Thanks as always!

**Comment by Dominic-Marcelino** [comment]
I do like the idea!
Thinking about adding to settings therefore:
1.) Add a label to the action-buttons
2.) Hide the field-value on the displa

**Comment by Dominic-Marcelino** [comment]
Released in [V.1.6](https://github.com/utomic-media/directus-extension-field-actions/releases/tag/v1.6.0)
