### ISSUE TITLE
Cannot read properties of null (reading 'matches')

### ISSUE THREAD

**Issue by franzpro** [utomic-media/directus-extension-field-actions#35]
Hi,

i tried to install the extension via:
 npm i directus-extension-field-actions

```
npm ERR! Cannot read properties of null (reading 'matches')
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-17T12_31_37_712Z-debug-0.log
```

the log File contains:

`0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/directus/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 9ms
17 timing npm:load:configload Completed in 9ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 4ms
20 verbose title npm i directus-extension-field-actions
21 verbose argv "i" "directus-extension-field-actions"
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 5ms
24 timing npm:load:display Completed in 6ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-04-17T12_08_54_128Z-
26 verbose logfile /root/.npm/_logs/2023-04-17T12_08_54_128Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 33ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 0ms
34 timing idealTree:init Completed in 6998ms
35 timing idealTree:userRequests Completed in 26ms
36 silly idealTree buildDeps
37 silly fetch manifest directus-extension-field-actions@*
38 http fetch GET 200 https://registry.npmjs.org/directus-extension-field-actions 464ms (cache miss)
39 silly fetch manifest @ngneat/falso@6.4.0
40 http fetch GET 200 https://registry.npmjs.org/@ngneat%2ffalso 929ms (cache miss)
41 silly fetch manifest @types/async@3.2.18
42 http fetch GET 200 https://registry.npmjs.org/@types%2fasync 1440ms (cache miss)
43 silly fetch manifest @types/busboy@1.5.0
44 http fetch GET 200 https://registry.npmjs.org/@types%2fbusboy 83ms (cache miss)
45 silly fetch manifest @types/bytes@3.1.1
46 http fetch GET 200 https://registry.npmjs.org/@types%2fbytes 70ms (cache miss)
47 silly fetch manifest @types/cookie-parser@1.4.3
48 http fetch GET 200 https://registry.npmjs.org/@types%2fcookie-parser 49ms (cache miss)
49 silly fetch manifest @types/cors@2.8.13
50 http fetch GET 200 https://registry.npmjs.org/@types%2fcors 50ms (cache miss)
51 silly fetch manifest @types/deep-diff@1.0.2
52 http fetch GET 200 https://registry.npmjs.org/@types%2fdeep-diff 1430ms (cache miss)
53 silly fetch manifest @types/destroy@1.0.0
54 http fetch GET 200 https://registry.npmjs.org/@types%2fdestroy 57ms (cache miss)
55 silly fetch manifest @types/encodeurl@1.0.0
56 http fetch GET 200 https://registry.npmjs.org/@types%2fencodeurl 68ms (cache miss)
57 silly fetch manifest @types/exif-reader@1.0.0
58 http fetch GET 200 https://registry.npmjs.org/@types%2fexif-reader 1377ms (cache miss)
59 silly fetch manifest @types/express@4.17.17
60 http fetch GET 200 https://registry.npmjs.org/@types%2fexpress 54ms (cache miss)
61 silly fetch manifest @types/express-serve-static-core@4.17.33
62 http fetch GET 200 https://registry.npmjs.org/@types%2fexpress-serve-static-core 54ms (cache miss)
63 silly fetch manifest @types/fast-redact@3.0.2
64 http fetch GET 200 https://registry.npmjs.org/@types%2ffast-redact 1415ms (cache miss)
65 silly fetch manifest @types/flat@5.0.2
66 http fetch GET 200 https://registry.npmjs.org/@types%2fflat 53ms (cache miss)
67 silly fetch manifest @types/fs-extra@11.0.1
68 http fetch GET 200 https://registry.npmjs.org/@types%2ffs-extra 82ms (cache miss)
69 silly fetch manifest @types/inquirer@8.2.6
70 http fetch GET 200 https://registry.npmjs.org/@types%2finquirer 1370ms (cache miss)
71 silly fetch manifest @types/js-yaml@4.0.5
72 http fetch GET 200 https://registry.npmjs.org/@types%2fjs-yaml 69ms (cache miss)
73 silly fetch manifest @types/json2csv@5.0.3
74 http fetch GET 200 https://registry.npmjs.org/@types%2fjson2csv 75ms (cache miss)
75 silly fetch manifest @types/jsonwebtoken@9.0.1
76 http fetch GET 200 https://registry.npmjs.org/@types%2fjsonwebtoken 43ms (cache miss)
77 silly fetch manifest @types/keyv@3.1.4
78 http fetch GET 200 https://registry.npmjs.org/@types%2fkeyv 64ms (cache miss)
79 silly fetch manifest @types/ldapjs@2.2.5
80 http fetch GET 200 https://registry.npmjs.org/@types%2fldapjs 1438ms (cache miss)
81 silly fetch manifest @types/lodash@4.14.191
82 http fetch GET 200 https://registry.npmjs.org/@types%2flodash 65ms (cache miss)
83 silly fetch manifest @types/marked@4.0.8
84 http fetch GET 200 https://registry.npmjs.org/@types%2fmarked 53ms (cache miss)
85 silly fetch manifest @types/mime-types@2.1.1
86 http fetch GET 200 https://registry.npmjs.org/@types%2fmime-types 58ms (cache miss)
87 silly fetch manifest @types/ms@0.7.31
88 http fetch GET 200 https://registry.npmjs.org/@types%2fms 51ms (cache miss)
89 silly fetch manifest @types/node@18.15.3
90 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 337ms (cache miss)
91 silly fetch manifest @types/node-cron@3.0.7
92 http fetch GET 200 https://registry.npmjs.org/@types%2fnode-cron 71ms (cache miss)
93 silly fetch manifest @types/nodemailer@6.4.7
94 http fetch GET 200 https://registry.npmjs.org/@types%2fnodemailer 52ms (cache miss)
95 silly fetch manifest @types/object-hash@3.0.2
96 http fetch GET 200 https://registry.npmjs.org/@types%2fobject-hash 65ms (cache miss)
97 silly fetch manifest @types/qs@6.9.7
98 http fetch GET 200 https://registry.npmjs.org/@types%2fqs 69ms (cache miss)
99 silly fetch manifest @types/sanitize-html@2.9.0
100 http fetch GET 200 https://registry.npmjs.org/@types%2fsanitize-html 914ms (cache miss)
101 silly fetch manifest @types/sharp@0.31.1
102 http fetch GET 200 https://registry.npmjs.org/@types%2fsharp 77ms (cache miss)
103 silly fetch manifest @types/stream-json@1.7.3
104 http fetch GET 200 https://registry.npmjs.org/@types%2fstream-json 880ms (cache miss)
105 silly fetch manifest @types/uuid@9.0.1
106 http fetch GET 200 https://registry.npmjs.org/@types%2fuuid 42ms (cache miss)
107 silly fetch manifest @types/uuid-validate@0.0.1
108 http fetch GET 200 https://registry.npmjs.org/@types%2fuuid-validate 1458ms (cache miss)
109 silly fetch manifest @types/wellknown@0.5.4
110 http fetch GET 200 https://registry.npmjs.org/@types%2fwellknown 1445ms (cache miss)
111 silly fetch manifest @vitest/coverage-c8@0.29.3
112 http fetch GET 200 https://registry.npmjs.org/@vitest%2fcoverage-c8 117ms (cache miss)
113 silly fetch manifest vitest@0.29.3
114 http fetch GET 200 https://registry.npmjs.org/vitest 62ms (cache miss)
115 silly fetch manifest @edge-runtime/vm@*
116 http fetch GET 200 https://registry.npmjs.org/@edge-runtime%2fvm 93ms (cache miss)
117 silly fetch manifest @vitest/browser@*
118 http fetch GET 200 https://registry.npmjs.org/@vitest%2fbrowser 109ms (cache miss)
119 silly fetch manifest vitest@>=0.29.4
120 silly fetch manifest @vitest/ui@*
121 http fetch GET 200 https://registry.npmjs.org/@vitest%2fui 110ms (cache miss)
122 silly fetch manifest happy-dom@*
123 http fetch GET 200 https://registry.npmjs.org/happy-dom 57ms (cache miss)
124 silly fetch manifest jsdom@*
125 http fetch GET 200 https://registry.npmjs.org/jsdom 47ms (cache miss)
126 silly fetch manifest canvas@^2.5.0
127 http fetch GET 200 https://registry.npmjs.org/canvas 39ms (cache miss)
128 silly fetch manifest playwright@*
129 http fetch GET 200 https://registry.npmjs.org/playwright 208ms (cache miss)
130 silly fetch manifest safaridriver@*
131 http fetch GET 200 https://registry.npmjs.org/safaridriver 741ms (cache miss)
132 silly fetch manifest webdriverio@*
133 http fetch GET 200 https://registry.npmjs.org/webdriverio 49ms (cache miss)
134 silly fetch manifest copyfiles@2.4.1
135 http fetch GET 200 https://registry.npmjs.org/copyfiles 72ms (cache miss)
136 silly fetch manifest form-data@4.0.0
137 http fetch GET 200 https://registry.npmjs.org/form-data 41ms (cache miss)
138 silly fetch manifest knex-mock-client@2.0.0
139 http fetch GET 200 https://registry.npmjs.org/knex-mock-client 743ms (cache miss)
140 silly fetch manifest knex@2.4.2
141 http fetch GET 200 https://registry.npmjs.org/knex 47ms (cache miss)
142 silly fetch manifest ts-node@10.9.1
143 http fetch GET 200 https://registry.npmjs.org/ts-node 43ms (cache miss)
144 silly fetch manifest @swc/core@>=1.2.50
145 http fetch GET 200 https://registry.npmjs.org/@swc%2fcore 92ms (cache miss)
146 silly fetch manifest @swc/helpers@^0.5.0
147 http fetch GET 200 https://registry.npmjs.org/@swc%2fhelpers 61ms (cache miss)
148 silly fetch manifest @swc/wasm@>=1.2.50
149 http fetch GET 200 https://registry.npmjs.org/@swc%2fwasm 65ms (cache miss)
150 silly fetch manifest typescript@4.9.5
151 http fetch GET 200 https://registry.npmjs.org/typescript 358ms (cache miss)
152 silly fetch manifest ts-node-dev@2.0.0
153 http fetch GET 200 https://registry.npmjs.org/ts-node-dev 35ms (cache miss)
154 silly fetch manifest node-notifier@*
155 http fetch GET 200 https://registry.npmjs.org/node-notifier 43ms (cache miss)
156 silly placeDep ROOT @ngneat/falso@6.4.0 OK for: directus@9.24.0 want: 6.4.0
157 silly placeDep ROOT @types/async@3.2.18 OK for: directus@9.24.0 want: 3.2.18
158 silly placeDep ROOT @types/busboy@1.5.0 OK for: directus@9.24.0 want: 1.5.0
159 silly placeDep ROOT @types/bytes@3.1.1 OK for: directus@9.24.0 want: 3.1.1
160 silly placeDep ROOT @types/cookie-parser@1.4.3 OK for: directus@9.24.0 want: 1.4.3
161 silly placeDep ROOT @types/cors@2.8.13 OK for: directus@9.24.0 want: 2.8.13
162 silly placeDep ROOT @types/deep-diff@1.0.2 OK for: directus@9.24.0 want: 1.0.2
163 silly placeDep ROOT @types/destroy@1.0.0 OK for: directus@9.24.0 want: 1.0.0
164 silly placeDep ROOT @types/encodeurl@1.0.0 OK for: directus@9.24.0 want: 1.0.0
165 silly placeDep ROOT @types/exif-reader@1.0.0 OK for: directus@9.24.0 want: 1.0.0
166 silly placeDep ROOT @types/express@4.17.17 OK for: directus@9.24.0 want: 4.17.17
167 silly placeDep ROOT @types/express-serve-static-core@4.17.33 OK for: directus@9.24.0 want: 4.17.33
168 silly placeDep ROOT @types/fast-redact@3.0.2 OK for: directus@9.24.0 want: 3.0.2
169 silly placeDep ROOT @types/flat@5.0.2 OK for: directus@9.24.0 want: 5.0.2
170 silly placeDep ROOT @types/fs-extra@11.0.1 OK for: directus@9.24.0 want: 11.0.1
171 silly placeDep ROOT @types/inquirer@8.2.6 OK for: directus@9.24.0 want: 8.2.6
172 silly placeDep ROOT @types/js-yaml@4.0.5 OK for: directus@9.24.0 want: 4.0.5
173 silly placeDep ROOT @types/json2csv@5.0.3 OK for: directus@9.24.0 want: 5.0.3
174 silly placeDep ROOT @types/jsonwebtoken@9.0.1 OK for: directus@9.24.0 want: 9.0.1
175 silly placeDep ROOT @types/keyv@3.1.4 OK for: directus@9.24.0 want: 3.1.4
176 silly placeDep ROOT @types/ldapjs@2.2.5 OK for: directus@9.24.0 want: 2.2.5
177 silly placeDep ROOT @types/lodash@4.14.191 OK for: directus@9.24.0 want: 4.14.191
178 silly placeDep ROOT @types/marked@4.0.8 OK for: directus@9.24.0 want: 4.0.8
179 silly placeDep ROOT @types/mime-types@2.1.1 OK for: directus@9.24.0 want: 2.1.1
180 silly placeDep ROOT @types/ms@0.7.31 OK for: directus@9.24.0 want: 0.7.31
181 silly placeDep ROOT @types/node@18.15.3 OK for: directus@9.24.0 want: 18.15.3
182 silly placeDep ROOT @types/node-cron@3.0.7 OK for: directus@9.24.0 want: 3.0.7
183 silly placeDep ROOT @types/nodemailer@6.4.7 OK for: directus@9.24.0 want: 6.4.7
184 silly placeDep ROOT @types/object-hash@3.0.2 OK for: directus@9.24.0 want: 3.0.2
185 silly placeDep ROOT @types/qs@6.9.7 OK for: directus@9.24.0 want: 6.9.7
186 silly placeDep ROOT @types/sanitize-html@2.9.0 OK for: directus@9.24.0 want: 2.9.0
187 silly placeDep ROOT @types/sharp@0.31.1 OK for: directus@9.24.0 want: 0.31.1
188 silly placeDep ROOT @types/stream-json@1.7.3 OK for: directus@9.24.0 want: 1.7.3
189 silly placeDep ROOT @types/uuid@9.0.1 OK for: directus@9.24.0 want: 9.0.1
190 silly placeDep ROOT @types/uuid-validate@0.0.1 OK for: directus@9.24.0 want: 0.0.1
191 silly placeDep ROOT @types/wellknown@0.5.4 OK for: directus@9.24.0 want: 0.5.4
192 silly placeDep ROOT @vitest/coverage-c8@0.29.3 OK for: directus@9.24.0 want: 0.29.3
193 silly placeDep ROOT vitest@0.29.3 OK for: @vitest/coverage-c8@0.29.3 want: >=0.29.0 <1
194 silly placeDep ROOT copyfiles@2.4.1 OK for: directus@9.24.0 want: 2.4.1
195 silly placeDep ROOT directus-extension-field-actions@1.5.1 OK for: directus@9.24.0 want: *
196 silly placeDep ROOT form-data@4.0.0 OK for: directus@9.24.0 want: 4.0.0
197 timing idealTree Completed in 27956ms
198 timing command:i Completed in 27972ms
199 verbose stack TypeError: Cannot read properties of null (reading 'matches')
199 verbose stack     at Link.matches (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1119:41)
199 verbose stack     at Link.canDedupe (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1073:15)
199 verbose stack     at PlaceDep.pruneDedupable (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:426:14)
199 verbose stack     at new PlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:278:14)
199 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:943:31
199 verbose stack     at Array.map (<anonymous>)
199 verbose stack     at [buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:943:8)
199 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
199 verbose stack     at async Promise.all (index 1)
199 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
200 verbose cwd /directus/extensions
201 verbose Linux 5.10.0-21-amd64
202 verbose node v18.15.0
203 verbose npm  v9.5.0
204 error Cannot read properties of null (reading 'matches')
205 verbose exit 1
206 timing npm Completed in 28099ms
207 verbose unfinished npm timer reify 1681733334246
208 verbose unfinished npm timer reify:loadTrees 1681733334249
209 verbose unfinished npm timer idealTree:buildDeps 1681733341275
210 verbose unfinished npm timer idealTree:#root 1681733341276
211 verbose code 1
212 error A complete log of this run can be found in:
212 error     /root/.npm/_logs/2023-04-17T12_08_54_128Z-debug-0.log`

can anybody help me with this message? 

thank you

Franz

**Comment by Dominic-Marcelino** [comment]
Looks like you're running into [this issue](https://github.com/npm/cli/issues/4819)
Please have a look into the suggestions in the comments.

In order to get more help, please provide a readable version of the log-file (proper line-breaks) as well as as many information as possible. 


1. How does your package.json looks like?
2. What version of npm are you using? (`npm -v`)
3. Have you tried to recreate your package-lock?

**Comment by Dominic-Marcelino** [comment]
This looks like you're trying to install the extension directly inside the directus repo. Not sure if this even works.

The error you're getting is not related to the extension.

If there's no specific reason to build the app by your own I'd recommend to check your setup and either install [directus as an dependency](https://docs.directus.io/self-hosted/cli.html#initialize-a-new-project) or use the [docker-version](https://docs.directus.io/self-hosted/docker-guide.html)

Feel free to re-open the issue if there's anything else related to the extension :)
