### ISSUE TITLE
the fields config is not work in defineDisplay

### ISSUE THREAD

**Issue by Helongzhou** [utomic-media/directus-extension-field-actions#37]
Hi , Thanks for the wonderful extension. we are exploring to use it heavily for our business logic implementaiton.

One question, follow the directus document [display](https://docs.directus.io/extensions/displays.html) 
_fields — If this option is set, the display will fetch relational fields. Can either be an array of fields or a function that returns an array of fields_

I set the fields in defineDisplay, but it is not work.
`
...
export default defineDisplay({
 ...
  fields: ['id', 'description', 'status', 'currency', 'amount']
})
`

**Comment by Dominic-Marcelino** [comment]
Hi @Helongzhou 
I assume you're trying to extend the extension and build it yourself?

Could you explain your use-case and what you're trying to archive further so that we can check if it's possible?

**Comment by Dominic-Marcelino** [comment]
I'll close this for now due to the lack of information. Feel free to re-open it with more context.
