### ISSUE TITLE
prefix aren't  indipendently for  the copy and link button

### ISSUE THREAD

**Issue by BflyD** [utomic-media/directus-extension-field-actions#41]
when a prefix is defined for the Link option, this is also reflected in the "copy" option, whether in "edit" or "display" mode

![Capture d’écran 2023-07-17 à 15 24 38](https://github.com/utomic-media/directus-extension-field-actions/assets/126342196/fd6c63ff-1a7a-4bb1-9a2b-1f874d4fbdf8)
![Capture d’écran 2023-07-17 à 15 25 24](https://github.com/utomic-media/directus-extension-field-actions/assets/126342196/97fd9c74-35ef-4a1e-9cbf-08af85e38da9)

**Comment by Dominic-Marcelino** [comment]
Thanks for reporting, will release a fix asap.

**Comment by BflyD** [comment]
in interface.vue, line 29
`v-tooltip="value ? 'Copy: ${computedLink}' : 'Can't copy empty value'"`

in file use-link.ts, the function systematically returns "linkPrefix"
