### ISSUE TITLE
Feature request: Actions to modify data of the item/field

### ISSUE THREAD

**Issue by vtisnado** [utomic-media/directus-extension-field-actions#44]
Hi guys,

I just discovered this extension and I really like it. I'm wondering if you have considered the option to add actions that interact with the data.

I think the Table layout is powerful to handle bulk or individual actions without the need to navigate each item one by one which could be tedious. For example, a category field could be a Dropdown instead of just a label. Other cases are true/false values than can show a Switch to quickly update the item.

There are other couple cases where I think adding the options I mentioned before could be helpful.

**Comment by Dominic-Marcelino** [comment]
Hi Victor,

we don't have any plans for such a feature right now. Directus currently differentiates between displays (_only displaying the data, used in tables and relational interfaces_) and interfaces (_used on item-views, allow editing an item_). 

The request would be a mixture of both, which easily could produce unwished side-effects when being used in different contexts.

There's two open feature request for directus regarding to this, which you can upvote:
- [Add a Spreadsheet Layout](https://github.com/directus/directus/discussions/3874)
- [Inline Editor](https://github.com/directus/directus/discussions/17937)

If those gets implemented we can re-check the possibilities.
I'll close the issue for now, feel free to re-open t once Directus has moved into it
