### ISSUE TITLE
how to use the extension

### ISSUE THREAD

**Issue by cyrsis** [utomic-media/directus-extension-field-actions#47]
Great extension,

Exactly what I need

<img width="942" alt="image" src="https://github.com/utomic-media/directus-extension-field-actions/assets/731087/8e7b9874-bf6a-4dfd-a31d-f6322fc56299">

I used docker-compose to install it

<img width="1150" alt="image" src="https://github.com/utomic-media/directus-extension-field-actions/assets/731087/731e8534-ebbd-4e8a-8fe1-840c40aa6012">

But I can not find anything new in the "Interface" nor "Display"

Directus 10.8.2

Thanks

**Comment by Dominic-Marcelino** [comment]
Hi Victor,

What is the type of your field? 
Are there any errors logged to the browsers console?

**Comment by cyrsis** [comment]
Hey Dominic

It just a simple "String"

No Errors , Nothing

<img width="890" alt="image" src="https://github.com/utomic-media/directus-extension-field-actions/assets/731087/a821f966-523f-4799-897f-1c311526e868">

**Comment by Dominic-Marcelino** [comment]
In that case we'll have to dig a bit deeper... Just re-checked but have running this extension in multiple Directus 10.8.2 instances.

Have you installed the extension via npm or from the extensions folder? 
Also: When you start your server, is there any error logged? Is it listed in the logs as loaded extension? (Directus logs a notice on server start` INFO: Loaded extensions: <the loaded extensions>`)

**Comment by cyrsis** [comment]
Sorry Dominic
it is the docker compose build. from the offical doc

Change to
```
docker compose build --no-cache

```  
Works!!!1
```
restart:
	docker compose down
	docker compose build --no-cache
	docker compose up -d

``
