### ISSUE TITLE
Not applicable for relational fields?

### ISSUE THREAD

**Issue by arladmin** [utomic-media/directus-extension-field-actions#49]
Is this extension not applicable for any of the relational fields (M2O, O2M, M2M)?
Or even the 'Files' field?

**Comment by Dominic-Marcelino** [comment]
Hi,

thanks for trying the extension. It supports text and numeric fields and won't support images or relational fields.
But you can use it as a display for a field inside your relational data, which should work fine.

What's your specific use-case? Maybe we can find even another solution.

**Comment by Dominic-Marcelino** [comment]
I'll close this issue for now. Feel free to open a new one if you encounter any specific issue.
